/* ============================================================
   CARD DATA  —  the ONLY file you edit to add content
   ------------------------------------------------------------
   Source: Rough Guide to Berlin — German section (pp. 160–162).
   Grouped into the book's own categories. Each category becomes
   its own lesson/unit on the home screen (with its own icon).

   Category shape:
   { category, icon, cards: [ {german, english, germanPhrase?, englishPhrase?} ] }
   Phrases are optional. German nouns are capitalised; adjectives
   and number words are lower-case (correct modern German).
   ============================================================ */

const DECK = [
  {
    category: "Greetings & basics",
    icon: "👋",
    cards: [
      { german: "ja",                       english: "yes" },
      { german: "nein",                      english: "no" },
      { german: "bitte",                     english: "please" },
      { german: "danke",                     english: "thank you" },
      { german: "Guten Morgen",              english: "good morning" },
      { german: "Guten Tag",                 english: "hello / good day" },
      { german: "Guten Abend",               english: "good evening" },
      { german: "Tschüss",                   english: "bye (informal)" },
      { german: "Auf Wiedersehen",           english: "goodbye" },
      { german: "Entschuldigen Sie, bitte",  english: "excuse me" },
    ],
  },
  {
    category: "Numbers",
    icon: "🔢",
    cards: [
      { german: "eins",            english: "1" },
      { german: "zwei",            english: "2" },
      { german: "drei",            english: "3" },
      { german: "vier",            english: "4" },
      { german: "fünf",            english: "5" },
      { german: "sechs",           english: "6" },
      { german: "sieben",          english: "7" },
      { german: "acht",            english: "8" },
      { german: "neun",            english: "9" },
      { german: "zehn",            english: "10" },
      { german: "elf",             english: "11" },
      { german: "zwölf",           english: "12" },
      { german: "dreizehn",        english: "13" },
      { german: "vierzehn",        english: "14" },
      { german: "fünfzehn",        english: "15" },
      { german: "sechzehn",        english: "16" },
      { german: "siebzehn",        english: "17" },
      { german: "achtzehn",        english: "18" },
      { german: "neunzehn",        english: "19" },
      { german: "zwanzig",         english: "20" },
      { german: "einundzwanzig",   english: "21" },
      { german: "zweiundzwanzig",  english: "22" },
      { german: "dreißig",         english: "30" },
      { german: "vierzig",         english: "40" },
      { german: "fünfzig",         english: "50" },
      { german: "sechzig",         english: "60" },
      { german: "siebzig",         english: "70" },
      { german: "achtzig",         english: "80" },
      { german: "neunzig",         english: "90" },
      { german: "hundert",         english: "100" },
      { german: "tausend",         english: "1000" },
    ],
  },
  {
    category: "Days & time",
    icon: "📅",
    cards: [
      { german: "heute",       english: "today" },
      { german: "gestern",     english: "yesterday" },
      { german: "morgen",      english: "tomorrow" },
      { german: "der Tag",     english: "day" },
      { german: "die Woche",   english: "week" },
      { german: "der Monat",   english: "month" },
      { german: "das Jahr",    english: "year" },
      { german: "das Wochenende", english: "weekend" },
      { german: "Montag",      english: "Monday" },
      { german: "Dienstag",    english: "Tuesday" },
      { german: "Mittwoch",    english: "Wednesday" },
      { german: "Donnerstag",  english: "Thursday" },
      { german: "Freitag",     english: "Friday" },
      { german: "Samstag",     english: "Saturday", englishPhrase: "also: Sonnabend" },
      { german: "Sonntag",     english: "Sunday" },
    ],
  },
  {
    category: "Getting around",
    icon: "🚉",
    cards: [
      { german: "Wo ist …?",           english: "where is …?" },
      { german: "der Eingang",         english: "entrance" },
      { german: "der Ausgang",         english: "exit" },
      { german: "die Toilette",        english: "toilet", englishPhrase: "also: das WC" },
      { german: "Damen",               english: "women / ladies" },
      { german: "Herren",              english: "men / gents" },
      { german: "das Hotel",           english: "hotel" },
      { german: "die Jugendherberge",  english: "youth hostel" },
      { german: "der Hauptbahnhof",    english: "main train station" },
      { german: "der Bus",             english: "bus" },
      { german: "der Zug",             english: "train" },
      { german: "das Flugzeug",        english: "plane" },
      { german: "rauchen / nicht rauchen", english: "smoking / no smoking" },
    ],
  },
  {
    category: "Useful phrases",
    icon: "💬",
    cards: [
      { german: "Ich verstehe nicht.",   english: "I don't understand." },
      { german: "Wieviel kostet …?",     english: "how much is …?" },
      { german: "Sprechen Sie Englisch?", english: "do you speak English?" },
      { german: "Ich spreche kein Deutsch.", english: "I don't speak German." },
      { german: "Ich hätte gern ein Bier.",  english: "I'd like a beer." },
      { german: "billig",   english: "cheap" },
      { german: "teuer",    english: "expensive" },
      { german: "offen / auf",       english: "open" },
      { german: "geschlossen / zu",  english: "closed" },
    ],
  },
  {
    category: "At the table",
    icon: "🍽️",
    cards: [
      { german: "das Frühstück",     english: "breakfast" },
      { german: "das Mittagessen",   english: "lunch" },
      { german: "das Abendessen",    english: "dinner" },
      { german: "Kaffee und Kuchen", english: "coffee and cakes" },
      { german: "das Messer",        english: "knife" },
      { german: "die Gabel",         english: "fork" },
      { german: "der Löffel",        english: "spoon" },
      { german: "der Teller",        english: "plate" },
      { german: "die Tasse",         english: "cup" },
      { german: "das Glas",          english: "glass" },
      { german: "die Speisekarte",   english: "menu" },
      { german: "die Vorspeise",     english: "starter" },
      { german: "das Hauptgericht",  english: "main course" },
      { german: "die Nachspeise",    english: "dessert" },
      { german: "die Rechnung",      english: "the bill" },
      { german: "Bio",               english: "organic" },
      { german: "vegetarisch",       english: "vegetarian" },
    ],
  },
  {
    category: "Food basics",
    icon: "🥖",
    cards: [
      { german: "das Brot",      english: "bread" },
      { german: "das Brötchen",  english: "bread roll" },
      { german: "die Butter",    english: "butter" },
      { german: "das Ei",        english: "egg" },
      { german: "der Essig",     english: "vinegar" },
      { german: "der Honig",     english: "honey" },
      { german: "der Joghurt",   english: "yoghurt" },
      { german: "der Käse",      english: "cheese" },
      { german: "der Kuchen",    english: "cake" },
      { german: "die Marmelade", english: "jam" },
      { german: "die Milch",     english: "milk" },
      { german: "das Öl",        english: "oil" },
      { german: "der Pfeffer",   english: "pepper" },
      { german: "der Reis",      english: "rice" },
      { german: "die Sahne",     english: "cream" },
      { german: "das Salz",      english: "salt" },
      { german: "scharf",        english: "spicy" },
      { german: "der Senf",      english: "mustard" },
      { german: "die Soße",      english: "sauce" },
      { german: "die Suppe",     english: "soup" },
      { german: "der Zucker",    english: "sugar" },
    ],
  },
  {
    category: "Drinks",
    icon: "🥤",
    cards: [
      { german: "das Bier",             english: "beer" },
      { german: "der Eiswürfel",        english: "ice cube" },
      { german: "die Flasche",          english: "bottle" },
      { german: "der Kaffee",           english: "coffee" },
      { german: "das Leitungswasser",   english: "tap water" },
      { german: "das Mineralwasser",    english: "mineral water" },
      { german: "der Saft",             english: "juice" },
      { german: "das Sprudelwasser",    english: "sparkling mineral water" },
      { german: "der Strohhalm",        english: "straw" },
      { german: "der Tee",              english: "tea" },
      { german: "die Teekanne",         english: "teapot" },
      { german: "der Wein",             english: "wine" },
      { german: "das Weißbier / Weizenbier", english: "wheat beer" },
    ],
  },
  {
    category: "Meat & fish",
    icon: "🍖",
    cards: [
      { german: "die Currywurst",   english: "curry sausage", englishPhrase: "with curry powder & ketchup" },
      { german: "die Forelle",      english: "trout" },
      { german: "die Garnelen",     english: "prawns" },
      { german: "Huhn / Hähnchen",  english: "chicken" },
      { german: "der Kabeljau",     english: "cod" },
      { german: "der Lachs",        english: "salmon" },
      { german: "das Lamm",         english: "lamb" },
      { german: "das Lammkotelett", english: "lamb chop" },
      { german: "die Leber",        english: "liver" },
      { german: "der Leberkäse",    english: "meatloaf" },
      { german: "die Makrele",      english: "mackerel" },
      { german: "das Rindfleisch",  english: "beef" },
      { german: "der Schinken",     english: "ham" },
      { german: "das Schweinefleisch", english: "pork" },
      { german: "der Speck",        english: "bacon" },
      { german: "der Thunfisch",    english: "tuna" },
      { german: "das Wiener Schnitzel", english: "breaded cutlet", englishPhrase: "usually veal, sometimes pork" },
      { german: "die Wurst",        english: "sausage" },
      { german: "der Zander",       english: "pikeperch" },
    ],
  },
  {
    category: "Vegetables",
    icon: "🥕",
    cards: [
      { german: "der Blumenkohl",       english: "cauliflower" },
      { german: "die Bohnen",           english: "beans" },
      { german: "die Bratkartoffeln",   english: "fried potatoes" },
      { german: "die Erbsen",           english: "peas" },
      { german: "grüne Bohnen",         english: "green beans" },
      { german: "die Gurke",            english: "cucumber / gherkin" },
      { german: "Karotten / Möhren",    english: "carrots" },
      { german: "die Kartoffel",        english: "potato" },
      { german: "der Knoblauch",        english: "garlic" },
      { german: "der Lauch (Porree)",   english: "leeks" },
      { german: "der Maiskolben",       english: "corn on the cob" },
      { german: "die Paprika",          english: "peppers" },
      { german: "Pilze / Champignons",  english: "mushrooms" },
      { german: "Pommes frites",        english: "chips / fries" },
      { german: "der Rosenkohl",        english: "Brussels sprouts" },
      { german: "der Rotkohl",          english: "red cabbage" },
      { german: "der Salat",            english: "salad" },
      { german: "die Salzkartoffeln",   english: "boiled potatoes" },
      { german: "das Sauerkraut",       english: "pickled cabbage" },
      { german: "der Spargel",          english: "asparagus", englishPhrase: "white asparagus popular in season" },
      { german: "die Tomaten",          english: "tomatoes" },
      { german: "die Zwiebeln",         english: "onions" },
    ],
  },
  {
    category: "Fruit",
    icon: "🍎",
    cards: [
      { german: "die Ananas",    english: "pineapple" },
      { german: "der Apfel",     english: "apple" },
      { german: "die Aprikose",  english: "apricot" },
      { german: "die Banane",    english: "banana" },
      { german: "die Birne",     english: "pear" },
      { german: "die Erdbeere",  english: "strawberry" },
      { german: "die Himbeere",  english: "raspberry" },
      { german: "die Kirsche",   english: "cherry" },
      { german: "die Melone",    english: "melon" },
      { german: "die Orange",    english: "orange" },
      { german: "der Pfirsich",  english: "peach" },
      { german: "die Pflaume",   english: "plum" },
      { german: "die Trauben",   english: "grapes" },
      { german: "die Zitrone",   english: "lemon" },
    ],
  },
  {
    category: "Desserts & cakes",
    icon: "🍰",
    cards: [
      { german: "das Eis",         english: "ice cream" },
      { german: "der Käsekuchen",  english: "cheesecake" },
      { german: "der Keks",        english: "biscuit" },
      { german: "der Kuchen",      english: "cake" },
      { german: "die Schokolade",  english: "chocolate" },
      { german: "die Torte",       english: "cake / tart" },
    ],
  },
  {
    category: "German specialities",
    icon: "🇩🇪",
    cards: [
      { german: "Knödel / Klöße",     english: "dumplings", englishPhrase: "poached potato or bread dumplings" },
      { german: "die Maultaschen",    english: "stuffed pasta", englishPhrase: "similar to ravioli" },
      { german: "der Quark",          english: "quark", englishPhrase: "a strained fresh cheese" },
      { german: "der Sauerbraten",    english: "pot roast", englishPhrase: "usually beef" },
      { german: "der Schweinsbraten", english: "roast pork" },
      { german: "die Spätzle",        english: "spätzle", englishPhrase: "soft egg noodles" },
    ],
  },
];

window.DECK = DECK;
